# Generated by Django 4.2.5 on 2023-09-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmonitordb',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
