# Generated by Django 4.2.5 on 2023-09-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_monitor', '0002_alter_networkmonitordb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkmonitordb',
            name='status',
            field=models.CharField(default='400', max_length=100),
        ),
    ]
