# Generated by Django 4.2.5 on 2023-09-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_monitor', '0004_alter_networkmonitordb_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkmonitordb',
            name='latency',
            field=models.FloatField(default=0),
        ),
    ]
